gacutil.exe -u "ComponentFactory.Krypton.Design.dll"
gacutil.exe -u "ComponentFactory.Krypton.Docking.dll"
gacutil.exe -u "ComponentFactory.Krypton.Navigator.dll"
gacutil.exe -u "ComponentFactory.Krypton.Ribbon.dll"
gacutil.exe -u "ComponentFactory.Krypton.Toolkit.dll"
gacutil.exe -u "ComponentFactory.Krypton.Workspace.dll"
